name: Build and Tests

on:
  push:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build the stack
        run: docker-compose up -d

      - name: Rubocop
        run: docker-compose run web bundle exec rubocop

      - name: erb linter
        run: bundle exec erblint --lint-all --enable-all-linters

      - name: Brakeman
        run: docker-compose run web bundle exec brakeman

      - name: Bundler audit
        run: docker-compose run web bundle exec bundler-audit

      - name: prepare database
        run: docker-compose run web bin/rails db:create db:migrate

      - name: run unit-tests
        run: docker-compose run web bin/rails test

      # todo chrome version not working, also no chrome in our container
      #- name: run system-tests
      #  run: bin/rails test:system