name: Build and Tests

on:
  push:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: enchan/baytown_news:latest
          cache-from: type=registry,ref=enchan/baytown_news:latest
          cache-to: type=inline

      - name: Build the stack
        run: docker-compose up -d

      - name: Rubocop
        run: docker-compose run web bundle exec rubocop

      - name: erb linter
        run: docker-compose run web bundle exec erblint --lint-all --enable-all-linters

      - name: Brakeman
        run: docker-compose run web bundle exec brakeman

      - name: Bundler audit
        run: docker-compose run web bundle exec bundler-audit

      - name: prepare database
        run: docker-compose run web bin/rails db:create db:migrate

      - name: run unit-tests
        run: docker-compose run web bin/rails test

      # todo chrome version not working, also no chrome in our container
      #- name: run system-tests
      #  run: bin/rails test:system